using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace x2tap.Utils
{
	public static class GeoIP
	{
		/// <summary>
		///		MaxMind 数据库
		/// </summary>
		public static MaxMind.GeoIP2.DatabaseReader Database;

		/// <summary>
		///		国家旗帜
		/// </summary>
		public static Dictionary<string, Bitmap> CountryImage = new Dictionary<string, Bitmap>()
		{
			{ "AD", Properties.Resources.flagAD },
			{ "AE", Properties.Resources.flagAE },
			{ "AF", Properties.Resources.flagAF },
			{ "AG", Properties.Resources.flagAG },
			{ "AL", Properties.Resources.flagAL },
			{ "AM", Properties.Resources.flagAM },
			{ "AO", Properties.Resources.flagAO },
			{ "AR", Properties.Resources.flagAR },
			{ "AT", Properties.Resources.flagAT },
			{ "AU", Properties.Resources.flagAU },
			{ "AZ", Properties.Resources.flagAZ },
			{ "BA", Properties.Resources.flagBA },
			{ "BB", Properties.Resources.flagBB },
			{ "BD", Properties.Resources.flagBD },
			{ "BE", Properties.Resources.flagBE },
			{ "BF", Properties.Resources.flagBF },
			{ "BG", Properties.Resources.flagBG },
			{ "BH", Properties.Resources.flagBH },
			{ "BI", Properties.Resources.flagBI },
			{ "BJ", Properties.Resources.flagBJ },
			{ "BN", Properties.Resources.flagBN },
			{ "BO", Properties.Resources.flagBO },
			{ "BR", Properties.Resources.flagBR },
			{ "BS", Properties.Resources.flagBS },
			{ "BT", Properties.Resources.flagBT },
			{ "BW", Properties.Resources.flagBW },
			{ "BY", Properties.Resources.flagBY },
			{ "BZ", Properties.Resources.flagBZ },
			{ "CA", Properties.Resources.flagCA },
			{ "CD", Properties.Resources.flagCD },
			{ "CF", Properties.Resources.flagCF },
			{ "CG", Properties.Resources.flagCG },
			{ "CH", Properties.Resources.flagCH },
			{ "CI", Properties.Resources.flagCI },
			{ "CL", Properties.Resources.flagCL },
			{ "CM", Properties.Resources.flagCM },
			{ "CN", Properties.Resources.flagCN },
			{ "CO", Properties.Resources.flagCO },
			{ "CR", Properties.Resources.flagCR },
			{ "CU", Properties.Resources.flagCU },
			{ "CV", Properties.Resources.flagCV },
			{ "CY", Properties.Resources.flagCY },
			{ "CZ", Properties.Resources.flagCZ },
			{ "DE", Properties.Resources.flagDE },
			{ "DJ", Properties.Resources.flagDJ },
			{ "DK", Properties.Resources.flagDK },
			{ "DM", Properties.Resources.flagDM },
			{ "DO", Properties.Resources.flagDO },
			{ "DZ", Properties.Resources.flagDZ },
			{ "EC", Properties.Resources.flagEC },
			{ "EE", Properties.Resources.flagEE },
			{ "EG", Properties.Resources.flagEG },
			{ "EH", Properties.Resources.flagEH },
			{ "ER", Properties.Resources.flagER },
			{ "ES", Properties.Resources.flagES },
			{ "ET", Properties.Resources.flagET },
			{ "FI", Properties.Resources.flagFI },
			{ "FJ", Properties.Resources.flagFJ },
			{ "FM", Properties.Resources.flagFM },
			{ "FR", Properties.Resources.flagFR },
			{ "GA", Properties.Resources.flagGA },
			{ "GB", Properties.Resources.flagGB },
			{ "GD", Properties.Resources.flagGD },
			{ "GE", Properties.Resources.flagGE },
			{ "GH", Properties.Resources.flagGH },
			{ "GM", Properties.Resources.flagGM },
			{ "GN", Properties.Resources.flagGN },
			{ "GQ", Properties.Resources.flagGQ },
			{ "GR", Properties.Resources.flagGR },
			{ "GT", Properties.Resources.flagGT },
			{ "GW", Properties.Resources.flagGW },
			{ "GY", Properties.Resources.flagGY },
			{ "HK", Properties.Resources.flagHK },
			{ "HN", Properties.Resources.flagHN },
			{ "HR", Properties.Resources.flagHR },
			{ "HT", Properties.Resources.flagHT },
			{ "HU", Properties.Resources.flagHU },
			{ "ID", Properties.Resources.flagID },
			{ "IE", Properties.Resources.flagIE },
			{ "IL", Properties.Resources.flagIL },
			{ "IN", Properties.Resources.flagIN },
			{ "IQ", Properties.Resources.flagIQ },
			{ "IR", Properties.Resources.flagIR },
			{ "IS", Properties.Resources.flagIS },
			{ "IT", Properties.Resources.flagIT },
			{ "JM", Properties.Resources.flagJM },
			{ "JO", Properties.Resources.flagJO },
			{ "JP", Properties.Resources.flagJP },
			{ "KE", Properties.Resources.flagKE },
			{ "KG", Properties.Resources.flagKG },
			{ "KH", Properties.Resources.flagKH },
			{ "KI", Properties.Resources.flagKI },
			{ "KM", Properties.Resources.flagKM },
			{ "KN", Properties.Resources.flagKN },
			{ "KP", Properties.Resources.flagKP },
			{ "KR", Properties.Resources.flagKR },
			{ "KS", Properties.Resources.flagKS },
			{ "KW", Properties.Resources.flagKW },
			{ "KZ", Properties.Resources.flagKZ },
			{ "LA", Properties.Resources.flagLA },
			{ "LB", Properties.Resources.flagLB },
			{ "LC", Properties.Resources.flagLC },
			{ "LI", Properties.Resources.flagLI },
			{ "LK", Properties.Resources.flagLK },
			{ "LR", Properties.Resources.flagLR },
			{ "LS", Properties.Resources.flagLS },
			{ "LT", Properties.Resources.flagLT },
			{ "LU", Properties.Resources.flagLU },
			{ "LV", Properties.Resources.flagLV },
			{ "LY", Properties.Resources.flagLY },
			{ "MA", Properties.Resources.flagMA },
			{ "MC", Properties.Resources.flagMC },
			{ "MD", Properties.Resources.flagMD },
			{ "ME", Properties.Resources.flagME },
			{ "MG", Properties.Resources.flagMG },
			{ "MH", Properties.Resources.flagMH },
			{ "MK", Properties.Resources.flagMK },
			{ "ML", Properties.Resources.flagML },
			{ "MM", Properties.Resources.flagMM },
			{ "MN", Properties.Resources.flagMN },
			{ "MR", Properties.Resources.flagMR },
			{ "MT", Properties.Resources.flagMT },
			{ "MU", Properties.Resources.flagMU },
			{ "MV", Properties.Resources.flagMV },
			{ "MW", Properties.Resources.flagMW },
			{ "MX", Properties.Resources.flagMX },
			{ "MY", Properties.Resources.flagMY },
			{ "MZ", Properties.Resources.flagMZ },
			{ "NA", Properties.Resources.flagNA },
			{ "NE", Properties.Resources.flagNE },
			{ "NG", Properties.Resources.flagNG },
			{ "NI", Properties.Resources.flagNI },
			{ "NL", Properties.Resources.flagNL },
			{ "NO", Properties.Resources.flagNO },
			{ "NP", Properties.Resources.flagNP },
			{ "NR", Properties.Resources.flagNR },
			{ "NZ", Properties.Resources.flagNZ },
			{ "OM", Properties.Resources.flagOM },
			{ "PA", Properties.Resources.flagPA },
			{ "PE", Properties.Resources.flagPE },
			{ "PG", Properties.Resources.flagPG },
			{ "PH", Properties.Resources.flagPH },
			{ "PK", Properties.Resources.flagPK },
			{ "PL", Properties.Resources.flagPL },
			{ "PT", Properties.Resources.flagPT },
			{ "PW", Properties.Resources.flagPW },
			{ "PY", Properties.Resources.flagPY },
			{ "QA", Properties.Resources.flagQA },
			{ "RO", Properties.Resources.flagRO },
			{ "RS", Properties.Resources.flagRS },
			{ "RU", Properties.Resources.flagRU },
			{ "RW", Properties.Resources.flagRW },
			{ "SA", Properties.Resources.flagSA },
			{ "SB", Properties.Resources.flagSB },
			{ "SC", Properties.Resources.flagSC },
			{ "SD", Properties.Resources.flagSD },
			{ "SE", Properties.Resources.flagSE },
			{ "SG", Properties.Resources.flagSG },
			{ "SI", Properties.Resources.flagSI },
			{ "SK", Properties.Resources.flagSK },
			{ "SL", Properties.Resources.flagSL },
			{ "SM", Properties.Resources.flagSM },
			{ "SN", Properties.Resources.flagSN },
			{ "SO", Properties.Resources.flagSO },
			{ "SR", Properties.Resources.flagSR },
			{ "ST", Properties.Resources.flagST },
			{ "SV", Properties.Resources.flagSV },
			{ "SY", Properties.Resources.flagSY },
			{ "SZ", Properties.Resources.flagSZ },
			{ "TD", Properties.Resources.flagTD },
			{ "TG", Properties.Resources.flagTG },
			{ "TH", Properties.Resources.flagTH },
			{ "TJ", Properties.Resources.flagTJ },
			{ "TL", Properties.Resources.flagTL },
			{ "TM", Properties.Resources.flagTM },
			{ "TN", Properties.Resources.flagTN },
			{ "TO", Properties.Resources.flagTO },
			{ "TR", Properties.Resources.flagTR },
			{ "TT", Properties.Resources.flagTT },
			{ "TV", Properties.Resources.flagTV },
			{ "TW", Properties.Resources.flagTW },
			{ "TZ", Properties.Resources.flagTZ },
			{ "UA", Properties.Resources.flagUA },
			{ "UG", Properties.Resources.flagUG },
			{ "US", Properties.Resources.flagUS },
			{ "UY", Properties.Resources.flagUY },
			{ "UZ", Properties.Resources.flagUZ },
			{ "VA", Properties.Resources.flagVA },
			{ "VC", Properties.Resources.flagVC },
			{ "VE", Properties.Resources.flagVE },
			{ "VN", Properties.Resources.flagVN },
			{ "VU", Properties.Resources.flagVU },
			{ "WS", Properties.Resources.flagWS },
			{ "YE", Properties.Resources.flagYE },
			{ "ZA", Properties.Resources.flagZA },
			{ "ZM", Properties.Resources.flagZM },
			{ "ZW", Properties.Resources.flagZW },
		};

		/// <summary>
		///		取 IP 国家 ISO 代码
		/// </summary>
		/// <param name="ip">IP</param>
		/// <returns></returns>
		public static string GetCountryISOCode(IPAddress ip)
		{
			return Database.Country(ip).Country.IsoCode;
		}

		public static Bitmap GetCountryImageByISOCode(string iso)
		{
			if (CountryImage.ContainsKey(iso))
			{
				return CountryImage[iso];
			}

			return CountryImage["CN"];
		}
	}
}
